export const authTypes = {
  POST_SIGN_PENDING: "POST_SIGN_PENDING",
  POST_SIGN_SUCCESS: "POST_SIGN_SUCCESS",
  POST_SIGN_FAILED: "POST_SIGN_FAILED",

  ALL_PRODUCT_PENDING: "ALL_PRODUCT_PENDING",
  ALL_PRODUCT_SUCCESS: "ALL_PRODUCT_SUCCESS",
  ALL_PRODUCT_FAILED: "ALL_PRODUCT_FAILED",

  SEARCH_PRODUCT_PENDING: "SEARCH_PRODUCT_PENDING",
  SEARCH_PRODUCT_SUCCESS: "SEARCH_PRODUCT_SUCCESS",
  SEARCH_PRODUCT_FAILED: "SEARCH_PRODUCT_FAILED",

  SINGLE_PRODUCT_PENDING: "SINGLE_PRODUCT_PENDING",
  SINGLE_PRODUCT_SUCCESS: "SINGLE_PRODUCT_SUCCESS",
  SINGLE_PRODUCT_FAILED: "SINGLE_PRODUCT_FAILED",
};
